Add etcd client wrapper.
elasticdeeplearning/edl pull request #69
Opened 2020-04-22 10:19 UTC by gongweibao

2020-04-22 12:31 UTC, wangxicoding requested changes

2020-04-22 12:31 UTC, wangxicoding commented on python/paddle_edl/discovery/etcd_client.py
> +        if key in self._leases():
self._leases不需要括号

2020-04-22 12:31 UTC, wangxicoding commented on python/paddle_edl/discovery/etcd_client.py
> +            self._etcd.revoke_lease(lease)
etcd 先revoke_lease还是先delete(key)？

2020-04-23 01:04 UTC, gongweibao commented on python/paddle_edl/discovery/etcd_client.py
> +        if key in self._leases():
Done.

2020-04-23 01:04 UTC, gongweibao commented on python/paddle_edl/discovery/etcd_client.py
> +            self._etcd.revoke_lease(lease)
Done.

2020-04-23 10:56 UTC, wangxicoding approved these changes
LGTM

2020-04-23 10:56 UTC, wangxicoding commented on python/paddle_edl/discovery/etcd_client.py
> +        random.shuffle(ep_lst)
为啥要shuffle，防止负载过高？

2020-04-23 11:28 UTC, gongweibao commented on python/paddle_edl/discovery/etcd_client.py
> +        random.shuffle(ep_lst)
嗯。虽然估计还是master节点在回复。不过，还是分散开请求吧。

2020-04-23 11:38 UTC, wangxicoding commented on python/paddle_edl/discovery/etcd_client.py
> +        random.shuffle(ep_lst)
java版的copycat我记得对raft协议有个优化，请求可以转发到follower上获取。

2020-04-24 01:24 UTC, gongweibao commented on python/paddle_edl/discovery/etcd_client.py
> +        random.shuffle(ep_lst)
我找找。

2020-04-26 11:37 UTC, gavin1332 approved these changes
LGTM

2020-04-26 11:47 UTC, gavin1332 approved these changes
AGAIN

2020-04-26 11:47 UTC, gavin1332 approved these changes
AGAIN AND AGAIN

2020-04-26 11:48 UTC, merged